//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExcel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUILDING
    {
        public int ID { get; set; }
        public Nullable<int> BUILDING_NAME { get; set; }
        public string CLASSROOM_NAME { get; set; }
    }
}
