//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExcel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public int COURSE_ID { get; set; }
        public string COURSE_NAME { get; set; }
        public string COURSE_THAI_NAME { get; set; }
        public string DEPARTMENT_NAME { get; set; }
    }
}
