//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExcel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTION
    {
        public int ID { get; set; }
        public string SUBJECT_ID { get; set; }
        public string SECTION_NUMBER { get; set; }
        public string SECTION_DATE { get; set; }
        public string SECTION_TIME { get; set; }
        public string SECTION_CLASSROOM { get; set; }
        public string SECTION_TEACHER { get; set; }
        public string SECTION_FACULTY { get; set; }
    }
}
