//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExcel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT
    {
        public int ID { get; set; }
        public string SUBJECT_ID { get; set; }
        public string SUBJECT_NAME { get; set; }
        public string SUBJECT_CREDIT { get; set; }
        public string SUBJECT_SECTION { get; set; }
        public string SUBJECT_DAY { get; set; }
        public string SUBJECT_TIME { get; set; }
        public string SUBJECT_CLASSROOM { get; set; }
        public string SUBJECT_TEACHER { get; set; }
        public string SUBJECT_SECT { get; set; }
        public string SUBJECT_YEAR { get; set; }
    }
}
